import json
from datetime import datetime
from core.base_agent import BaseAgent

# Fields to skip in the report (internal, too large, or DataFrame objects)
_SKIP_FIELDS = {"price_history_csv", "price_df", "spy_df", "source"}


class ReportAgent(BaseAgent):
    def __init__(self):
        super().__init__("ReportAgent")

    def run(self, ticker: str, **kwargs) -> dict:
        all_results = kwargs.get("all_results", {})

        lines = []
        lines.append(f"# {ticker} — Finance Expert Team Report")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

        for agent_name, result in all_results.items():
            if not isinstance(result, dict):
                continue
            lines.append(f"## {agent_name}")
            if result.get("error"):
                lines.append(f"ERROR: {result['error']}\n")
                continue
            data = result.get("data", {})
            for key, val in data.items():
                if key in _SKIP_FIELDS or val is None:
                    continue
                # Skip DataFrame objects
                if hasattr(val, "iloc"):
                    continue
                if isinstance(val, float):
                    if any(k in key for k in ["return", "drawdown", "volatility", "growth", "yield", "rate", "var_"]):
                        lines.append(f"- **{key}**: {val:.2%}")
                    else:
                        lines.append(f"- **{key}**: {val:.4f}")
                elif isinstance(val, list):
                    lines.append(f"- **{key}**:")
                    for item in val:
                        lines.append(f"  - {item}")
                elif isinstance(val, dict):
                    lines.append(f"- **{key}**: {json.dumps(val)}")
                else:
                    lines.append(f"- **{key}**: {val}")
            lines.append("")

        lines.append("---")
        lines.append("*This report is generated by Finance Expert Team for educational purposes only.*")
        lines.append("*It does not constitute financial advice. Always do your own research.*")

        report = "\n".join(lines)
        return self._result(ticker, {"report_text": report})
